CELESTIAL_DATABASE: dict = {
    "planets": {
        "mercury": {
            "type": "planet", "subtype": "terrestrial", "solar_system": True,
            "distance_from_sun_au": 0.39, "diameter_km": 4879, "mass_kg": 3.30e23,
            "gravity_m_s2": 3.7, "orbital_period_days": 88, "rotation_period_hours": 1407.6,
            "moons": 0, "rings": False, "surface_temp_range_c": [-180, 430],
            "atmosphere": "extremely thin (sodium, oxygen, hydrogen)",
            "discovery": "known since antiquity",
            "missions": ["Mariner 10", "MESSENGER", "BepiColombo (ongoing)"],
            "fun_facts": [
                "Smallest planet in the solar system",
                "Has the largest temperature swings of any planet",
                "A day on Mercury is longer than its year",
                "Has water ice in permanently shadowed craters near poles",
            ],
        },
        "venus": {
            "type": "planet", "subtype": "terrestrial", "solar_system": True,
            "distance_from_sun_au": 0.72, "diameter_km": 12104, "mass_kg": 4.87e24,
            "gravity_m_s2": 8.87, "orbital_period_days": 225, "rotation_period_hours": -5832,
            "moons": 0, "rings": False, "surface_temp_c": 465,
            "atmosphere": "thick CO2 with sulfuric acid clouds, 92 bar pressure",
            "discovery": "known since antiquity",
            "missions": ["Venera series", "Magellan", "DAVINCI+ (upcoming)", "EnVision (upcoming)"],
            "fun_facts": [
                "Hottest planet despite not being closest to the Sun (runaway greenhouse effect)",
                "Rotates backwards (retrograde) compared to most planets",
                "A Venusian day is longer than its year",
                "Surface pressure equivalent to 900m underwater on Earth",
            ],
        },
        "earth": {
            "type": "planet", "subtype": "terrestrial", "solar_system": True,
            "distance_from_sun_au": 1.0, "diameter_km": 12756, "mass_kg": 5.97e24,
            "gravity_m_s2": 9.81, "orbital_period_days": 365.25, "rotation_period_hours": 23.93,
            "moons": 1, "rings": False, "surface_temp_range_c": [-89, 58],
            "atmosphere": "N2 (78%), O2 (21%), Ar (0.93%), CO2 (0.04%)",
            "discovery": "home",
            "missions": ["countless Earth observation satellites"],
            "fun_facts": [
                "Only known planet to harbor life",
                "71% of surface covered by water",
                "Has a powerful magnetic field protecting life from solar radiation",
                "Located in the Goldilocks zone — just right for liquid water",
            ],
        },
        "mars": {
            "type": "planet", "subtype": "terrestrial", "solar_system": True,
            "distance_from_sun_au": 1.52, "diameter_km": 6779, "mass_kg": 6.39e23,
            "gravity_m_s2": 3.72, "orbital_period_days": 687, "rotation_period_hours": 24.6,
            "moons": 2, "rings": False, "surface_temp_range_c": [-125, 20],
            "atmosphere": "thin CO2 (0.6% of Earth pressure)",
            "discovery": "known since antiquity",
            "missions": ["Viking 1 & 2", "Pathfinder", "Spirit", "Opportunity", "Curiosity (active)", "Perseverance (active)", "Ingenuity helicopter"],
            "fun_facts": [
                "Has Olympus Mons, the largest volcano in the solar system (21 km high)",
                "Has Valles Marineris, a canyon system as wide as the USA",
                "Evidence of liquid water in the ancient past",
                "Two small moons: Phobos and Deimos",
            ],
        },
        "jupiter": {
            "type": "planet", "subtype": "gas_giant", "solar_system": True,
            "distance_from_sun_au": 5.2, "diameter_km": 142984, "mass_kg": 1.90e27,
            "gravity_m_s2": 24.79, "orbital_period_days": 4333, "rotation_period_hours": 9.93,
            "moons": 95, "rings": True, "core_temp_c": 24000,
            "atmosphere": "H2 (89%), He (10%), methane, ammonia, water",
            "discovery": "known since antiquity",
            "missions": ["Pioneer 10 & 11", "Voyager 1 & 2", "Galileo", "Juno (active)", "Europa Clipper (en route)"],
            "fun_facts": [
                "Great Red Spot: a storm larger than Earth, raging for 350+ years",
                "More than 2x more massive than all other planets combined",
                "Has 95 known moons including Europa (life candidate)",
                "Acts as a 'cosmic vacuum cleaner' protecting inner planets",
            ],
        },
        "saturn": {
            "type": "planet", "subtype": "gas_giant", "solar_system": True,
            "distance_from_sun_au": 9.58, "diameter_km": 120536, "mass_kg": 5.68e26,
            "gravity_m_s2": 10.44, "orbital_period_days": 10759, "rotation_period_hours": 10.7,
            "moons": 146, "rings": True, "ring_span_km": 282000,
            "atmosphere": "H2 (96%), He (3%)",
            "discovery": "known since antiquity",
            "missions": ["Pioneer 11", "Voyager 1 & 2", "Cassini-Huygens"],
            "fun_facts": [
                "Least dense planet — would float in water",
                "Rings made of ice and rock, extending 282,000 km",
                "Has 146 known moons — most of any planet",
                "Titan has liquid methane lakes and a thick atmosphere",
            ],
        },
        "uranus": {
            "type": "planet", "subtype": "ice_giant", "solar_system": True,
            "distance_from_sun_au": 19.2, "diameter_km": 51118, "mass_kg": 8.68e25,
            "gravity_m_s2": 8.69, "orbital_period_days": 30589, "rotation_period_hours": -17.24,
            "moons": 28, "rings": True,
            "atmosphere": "H2, He, methane (gives blue-green color)",
            "discovery": "1781 by William Herschel",
            "missions": ["Voyager 2 (1986 flyby)"],
            "fun_facts": [
                "Tilted 98 degrees on its side — rolls around the Sun like a bowling ball",
                "Coldest planetary atmosphere (-224 C)",
                "Has 13 known rings",
                "Moons named after Shakespeare and Alexander Pope characters",
            ],
        },
        "neptune": {
            "type": "planet", "subtype": "ice_giant", "solar_system": True,
            "distance_from_sun_au": 30.1, "diameter_km": 49528, "mass_kg": 1.02e26,
            "gravity_m_s2": 11.15, "orbital_period_days": 59800, "rotation_period_hours": 16.11,
            "moons": 16, "rings": True, "wind_speed_km_h": 2100,
            "atmosphere": "H2, He, methane",
            "discovery": "1846 (predicted mathematically)",
            "missions": ["Voyager 2 (1989 flyby)"],
            "fun_facts": [
                "Strongest winds in the solar system (2100 km/h)",
                "First planet found through mathematical prediction",
                "Great Dark Spot: a storm the size of Earth",
                "Triton orbits backwards and will eventually be torn apart",
            ],
        },
        "proxima centauri b": {
            "type": "planet", "subtype": "exoplanet_terrestrial", "solar_system": False,
            "host_star": "Proxima Centauri", "distance_from_earth_ly": 4.24,
            "orbital_period_days": 11.2, "mass_earth": 1.17, "potentially_habitable": True,
            "discovery": "2016", "discovery_method": "radial velocity",
            "fun_facts": [
                "Closest known exoplanet to Earth",
                "In the habitable zone of Proxima Centauri",
                "Likely tidally locked — one face always toward star",
                "Subject of Breakthrough Starshot interstellar mission proposal",
            ],
        },
        "kepler-452b": {
            "type": "planet", "subtype": "exoplanet_super_earth", "solar_system": False,
            "host_star": "Kepler-452", "distance_from_earth_ly": 1400,
            "orbital_period_days": 385, "diameter_earth": 1.63, "mass_earth": 5.0,
            "potentially_habitable": True, "discovery": "2015", "discovery_method": "transit",
            "fun_facts": [
                "Called 'Earth's cousin' — similar orbit period around sun-like star",
                "1,400 light-years away in the constellation Cygnus",
                "60% larger than Earth",
                "Its star is 6 billion years old vs Earth's 4.5 billion",
            ],
        },
        "trappist-1e": {
            "type": "planet", "subtype": "exoplanet_terrestrial", "solar_system": False,
            "host_star": "TRAPPIST-1", "distance_from_earth_ly": 39,
            "orbital_period_days": 6.1, "diameter_earth": 0.92, "mass_earth": 0.77,
            "potentially_habitable": True, "discovery": "2017", "discovery_method": "transit",
            "fun_facts": [
                "Best candidate for habitability in the TRAPPIST-1 system",
                "Receives similar stellar flux to Earth",
                "One of seven Earth-sized planets around the same star",
                "JWST is actively studying its atmosphere",
            ],
        },
        "trappist-1f": {
            "type": "planet", "subtype": "exoplanet_terrestrial", "solar_system": False,
            "host_star": "TRAPPIST-1", "distance_from_earth_ly": 39,
            "orbital_period_days": 9.2, "diameter_earth": 1.04, "mass_earth": 1.07,
            "potentially_habitable": True, "discovery": "2017", "discovery_method": "transit",
            "fun_facts": [
                "Outer habitable zone planet in the TRAPPIST-1 system",
                "May host liquid water on its surface",
                "Part of the most studied planetary system outside the solar system",
                "All seven TRAPPIST-1 planets fit within Mercury's orbit around our Sun",
            ],
        },
        "kepler-186f": {
            "type": "planet", "subtype": "exoplanet_terrestrial", "solar_system": False,
            "host_star": "Kepler-186", "distance_from_earth_ly": 582,
            "orbital_period_days": 130, "diameter_earth": 1.17,
            "potentially_habitable": True, "discovery": "2014", "discovery_method": "transit",
            "fun_facts": [
                "First Earth-sized planet confirmed in the habitable zone",
                "Orbits an M-dwarf star 582 light-years away",
                "Receives about 1/3 of the solar energy Earth gets",
                "Considered a landmark discovery in the search for life",
            ],
        },
        "k2-18b": {
            "type": "planet", "subtype": "exoplanet_hycean", "solar_system": False,
            "host_star": "K2-18", "distance_from_earth_ly": 124,
            "orbital_period_days": 33, "diameter_earth": 2.37, "mass_earth": 8.6,
            "discovery": "2015", "discovery_method": "transit",
            "fun_facts": [
                "JWST detected carbon dioxide and methane in its atmosphere",
                "Possible 'Hycean' world — hydrogen ocean beneath hydrogen atmosphere",
                "Traces of dimethyl sulfide possibly detected (biological marker on Earth)",
                "One of the most promising candidates for atmospheric biosignatures",
            ],
        },
        "hd 189733b": {
            "type": "planet", "subtype": "exoplanet_hot_jupiter", "solar_system": False,
            "host_star": "HD 189733", "distance_from_earth_ly": 64,
            "orbital_period_days": 2.22, "diameter_earth": 12.8, "mass_earth": 361,
            "surface_temp_k": 1200,
            "discovery": "2005", "discovery_method": "transit",
            "fun_facts": [
                "It rains liquid glass sideways at 9,000 km/h",
                "Vivid blue color from silicate particles in its atmosphere",
                "One of the most studied exoplanet atmospheres",
                "Orbits its star every 2.2 days — scorchingly close",
            ],
        },
        "55 cancri e": {
            "type": "planet", "subtype": "exoplanet_super_earth", "solar_system": False,
            "host_star": "55 Cancri A", "distance_from_earth_ly": 41,
            "orbital_period_days": 0.74, "diameter_earth": 1.88, "mass_earth": 8.08,
            "surface_temp_k": 2700,
            "discovery": "2004", "discovery_method": "radial velocity",
            "fun_facts": [
                "Nicknamed 'diamond planet' for possible carbon interior",
                "Orbits its star in just 18 hours",
                "Tidally locked with a magma ocean on the dayside",
                "JWST observed possible volcanic activity from thermal emission",
            ],
        },
        "wasp-12b": {
            "type": "planet", "subtype": "exoplanet_ultra_hot_jupiter", "solar_system": False,
            "host_star": "WASP-12", "distance_from_earth_ly": 1400,
            "orbital_period_days": 1.09, "diameter_earth": 19.5,
            "surface_temp_k": 2600, "discovery": "2008",
            "fun_facts": [
                "Being torn apart by its star's tidal forces",
                "Will be completely consumed by its host star in ~3 million years",
                "Absorbs 94% of starlight — one of the darkest exoplanets known",
                "Its elongated shape is visible from the asymmetric transit light curve",
            ],
        },
        "pluto": {
            "type": "planet", "subtype": "dwarf_planet", "solar_system": True,
            "distance_from_sun_au": 39.5, "diameter_km": 2377, "mass_kg": 1.30e22,
            "orbital_period_years": 248, "moons": 5, "surface_temp_c": -230,
            "atmosphere": "thin N2, methane, CO",
            "discovery": "1930 by Clyde Tombaugh",
            "missions": ["New Horizons (2015 flyby)"],
            "fun_facts": [
                "Reclassified from planet to dwarf planet in 2006",
                "Has a heart-shaped region called Tombaugh Regio",
                "Its moon Charon is so large the pair are considered a double system",
                "New Horizons revealed mountains, plains, and a thin blue atmosphere haze",
            ],
        },
        "eris": {
            "type": "planet", "subtype": "dwarf_planet", "solar_system": True,
            "distance_from_sun_au": 96.4, "diameter_km": 2326, "mass_kg": 1.66e22,
            "discovery": "2005 by Mike Brown et al.",
            "fun_facts": [
                "More massive than Pluto — its discovery led to Pluto's demotion",
                "Has one moon: Dysnomia",
                "Currently near aphelion — furthest point from Sun",
                "Named after the goddess of strife and discord",
            ],
        },
    },
    "stars": {
        "sun": {
            "type": "star", "spectral_class": "G2V", "solar_system": True,
            "diameter_km": 1392700, "mass_kg": 1.989e30, "age_billion_years": 4.6,
            "surface_temp_k": 5778, "core_temp_k": 15000000, "luminosity_solar": 1.0,
            "distance_from_earth_au": 0,
            "stage": "main sequence", "estimated_remaining_life_billion_years": 5.0,
            "fun_facts": [
                "Contains 99.86% of the solar system's total mass",
                "Light takes 8 minutes 20 seconds to reach Earth",
                "Will expand into a red giant in ~5 billion years",
                "Completes one galactic orbit every 225-250 million years",
            ],
        },
        "sirius": {
            "type": "star", "spectral_class": "A1V", "binary": True,
            "companion": "Sirius B (white dwarf)", "distance_from_earth_ly": 8.6,
            "diameter_solar": 1.711, "mass_solar": 2.063, "surface_temp_k": 9940,
            "luminosity_solar": 25.4, "constellation": "Canis Major",
            "apparent_magnitude": -1.46,
            "fun_facts": [
                "Brightest star in the night sky",
                "Part of a binary system with a white dwarf companion",
                "Ancient Egyptians used its rising to predict Nile floods",
                "Also called the Dog Star",
            ],
        },
        "betelgeuse": {
            "type": "star", "spectral_class": "M1-2 Ia-ab", "subtype": "red supergiant",
            "distance_from_earth_ly": 700, "diameter_solar": 764, "mass_solar": "16.5-19",
            "surface_temp_k": 3500, "luminosity_solar": 100000,
            "constellation": "Orion", "apparent_magnitude": 0.5,
            "supernova_risk": "imminent (astronomically speaking)",
            "fun_facts": [
                "So large it would extend past Jupiter's orbit at our Sun's location",
                "Experienced dramatic 'Great Dimming' in 2019-2020",
                "Will explode as a supernova within 100,000 years",
                "9th brightest star, visible to naked eye",
            ],
        },
        "proxima centauri": {
            "type": "star", "spectral_class": "M5.5Ve", "subtype": "red dwarf",
            "distance_from_earth_ly": 4.24, "diameter_solar": 0.154, "mass_solar": 0.1221,
            "surface_temp_k": 3042, "luminosity_solar": 0.0017,
            "constellation": "Centaurus", "age_billion_years": 4.85,
            "fun_facts": [
                "Closest star to the Sun",
                "Part of the Alpha Centauri triple star system",
                "Hosts Proxima Centauri b, a potentially habitable exoplanet",
                "Emits powerful flares that may threaten planetary habitability",
            ],
        },
        "vega": {
            "type": "star", "spectral_class": "A0Va", "distance_from_earth_ly": 25,
            "diameter_solar": 2.36, "mass_solar": 2.135, "surface_temp_k": 9602,
            "luminosity_solar": 40.12, "constellation": "Lyra", "apparent_magnitude": 0.03,
            "fun_facts": [
                "Second brightest star in the northern hemisphere",
                "Spins so fast it's 20% wider at equator than poles",
                "Was the North Star 14,000 years ago and will be again in 12,000 years",
                "Featured in Carl Sagan's 'Contact'",
            ],
        },
        "polaris": {
            "type": "star", "spectral_class": "F7Ib", "subtype": "yellow supergiant",
            "distance_from_earth_ly": 433, "mass_solar": 5.4, "surface_temp_k": 6015,
            "luminosity_solar": 2500, "constellation": "Ursa Minor",
            "common_name": "North Star / Pole Star",
            "fun_facts": [
                "Currently within 0.7 degrees of the celestial north pole",
                "A triple star system (Polaris A, Ab, B)",
                "Used for navigation for millennia",
                "Will be replaced as North Star by Gamma Cephei around 3000 CE",
            ],
        },
        "rigel": {
            "type": "star", "spectral_class": "B8Ia", "subtype": "blue supergiant",
            "distance_from_earth_ly": 863, "diameter_solar": 78.9, "mass_solar": 21,
            "surface_temp_k": 12100, "luminosity_solar": 120000,
            "constellation": "Orion", "apparent_magnitude": 0.13,
            "fun_facts": [
                "Brightest star in Orion despite being named 'Beta Orionis'",
                "120,000 times more luminous than the Sun",
                "Will end as a spectacular supernova",
                "Named from Arabic: 'the left leg of the Great One'",
            ],
        },
        "antares": {
            "type": "star", "spectral_class": "M1.5Iab-Ib", "subtype": "red supergiant",
            "distance_from_earth_ly": 550, "diameter_solar": 700, "mass_solar": 12,
            "surface_temp_k": 3400, "luminosity_solar": 57500,
            "constellation": "Scorpius", "apparent_magnitude": 1.06,
            "fun_facts": [
                "Name means 'rival of Ares (Mars)' due to its reddish color",
                "Diameter would reach beyond Mars if placed at the Sun",
                "One of the largest stars visible to the naked eye",
                "Will explode as a supernova within the next million years",
            ],
        },
        "alpha centauri a": {
            "type": "star", "spectral_class": "G2V", "subtype": "yellow dwarf",
            "distance_from_earth_ly": 4.37, "diameter_solar": 1.22, "mass_solar": 1.1,
            "surface_temp_k": 5790, "luminosity_solar": 1.519,
            "constellation": "Centaurus", "binary_system": "Alpha Centauri",
            "fun_facts": [
                "Part of the closest star system to our Sun",
                "Very similar to our own Sun in size, mass, and temperature",
                "Forms a binary pair with Alpha Centauri B",
                "Proposed target for Project Breakthrough Starshot",
            ],
        },
        "alpha centauri b": {
            "type": "star", "spectral_class": "K1V", "subtype": "orange dwarf",
            "distance_from_earth_ly": 4.37, "diameter_solar": 0.86, "mass_solar": 0.907,
            "surface_temp_k": 5260, "luminosity_solar": 0.5,
            "constellation": "Centaurus",
            "fun_facts": [
                "Companion star to Alpha Centauri A in a tight binary",
                "Cooler and dimmer than our Sun but still very similar",
                "Orbits Alpha Centauri A every 79.9 years",
                "Third brightest star in the night sky as part of the Alpha Centauri system",
            ],
        },
        "barnard's star": {
            "type": "star", "spectral_class": "M4Ve", "subtype": "red dwarf",
            "distance_from_earth_ly": 5.96, "diameter_solar": 0.196, "mass_solar": 0.144,
            "surface_temp_k": 3134, "luminosity_solar": 0.0035,
            "constellation": "Ophiuchus",
            "fun_facts": [
                "Has the highest proper motion of any star — visibly moves across the sky",
                "Second closest star system to the Sun",
                "Will be the closest star to Earth in ~10,000 years",
                "Long claimed to have planets — subject of ongoing study",
            ],
        },
        "wolf 359": {
            "type": "star", "spectral_class": "M6Ve", "subtype": "red dwarf flare star",
            "distance_from_earth_ly": 7.78, "diameter_solar": 0.16, "mass_solar": 0.09,
            "surface_temp_k": 2800, "luminosity_solar": 0.001,
            "constellation": "Leo",
            "fun_facts": [
                "One of the faintest stars known — invisible without a telescope",
                "Famous from Star Trek: site of the Battle of Wolf 359",
                "Emits powerful flares despite its tiny size",
                "5th closest star system to the Sun",
            ],
        },
        "canopus": {
            "type": "star", "spectral_class": "F0Ib", "subtype": "white supergiant",
            "distance_from_earth_ly": 313, "diameter_solar": 71, "mass_solar": 8.0,
            "surface_temp_k": 7400, "luminosity_solar": 10700,
            "constellation": "Carina", "apparent_magnitude": -0.74,
            "fun_facts": [
                "Second brightest star in the night sky after Sirius",
                "Used by spacecraft for navigation (gyroscope reference)",
                "Invisible from most of the Northern Hemisphere",
                "Was once the pole star for the ancient Egyptians",
            ],
        },
        "deneb": {
            "type": "star", "spectral_class": "A2Ia", "subtype": "blue-white supergiant",
            "distance_from_earth_ly": 2600, "diameter_solar": 203, "mass_solar": 20,
            "surface_temp_k": 8525, "luminosity_solar": 196000,
            "constellation": "Cygnus", "apparent_magnitude": 1.25,
            "fun_facts": [
                "Most luminous star in the local neighborhood of the Milky Way",
                "If Deneb were as close as Sirius, it would cast shadows at night",
                "Top of the Northern Cross asterism and the Summer Triangle",
                "Will likely end as a supernova",
            ],
        },
        "aldebaran": {
            "type": "star", "spectral_class": "K5III", "subtype": "red giant",
            "distance_from_earth_ly": 65, "diameter_solar": 44.2, "mass_solar": 1.16,
            "surface_temp_k": 3910, "luminosity_solar": 518,
            "constellation": "Taurus", "apparent_magnitude": 0.85,
            "fun_facts": [
                "Name means 'the follower' (following the Pleiades)",
                "Diameter would extend beyond Earth's orbit if placed at the Sun",
                "One of the four royal stars of ancient Persia",
                "Pioneer 10 spacecraft is headed in its general direction",
            ],
        },
        "fomalhaut": {
            "type": "star", "spectral_class": "A3V", "subtype": "white dwarf progenitor",
            "distance_from_earth_ly": 25, "diameter_solar": 1.84, "mass_solar": 1.92,
            "surface_temp_k": 8590, "luminosity_solar": 16.6,
            "constellation": "Piscis Austrinus", "apparent_magnitude": 1.16,
            "fun_facts": [
                "First star with a directly imaged debris disk",
                "Hubble photographed a candidate exoplanet (Fomalhaut b) in 2008",
                "Has one of the brightest and most prominent debris disks",
                "Known as 'the loneliest star' — no bright stars nearby",
            ],
        },
        "spica": {
            "type": "star", "spectral_class": "B1III-IV + B2V", "subtype": "binary blue giant",
            "distance_from_earth_ly": 250, "diameter_solar": 7.4, "mass_solar": 10.25,
            "surface_temp_k": 22400, "luminosity_solar": 12100,
            "constellation": "Virgo", "apparent_magnitude": 0.97,
            "fun_facts": [
                "Brightest star in Virgo and 15th brightest in the sky",
                "A close binary — two massive stars orbit each other every 4 days",
                "So close they are tidally distorted into egg shapes",
                "Hipparchus used it to discover Earth's precession in 127 BC",
            ],
        },
        "eta carinae": {
            "type": "star", "spectral_class": "LBV", "subtype": "luminous blue variable hypernova candidate",
            "distance_from_earth_ly": 7500, "diameter_solar": 250, "mass_solar": 120,
            "surface_temp_k": 40000, "luminosity_solar": 5000000,
            "constellation": "Carina",
            "fun_facts": [
                "One of the most massive and luminous stars in the Milky Way",
                "Underwent a 'Great Eruption' in 1843 — briefly the second brightest star in the sky",
                "A hypernova or gamma-ray burst candidate — could threaten life on Earth if aimed at us",
                "Surrounded by the Homunculus Nebula — its own ejected material",
            ],
        },
        "uy scuti": {
            "type": "star", "spectral_class": "M4Ia", "subtype": "red hypergiant",
            "distance_from_earth_ly": 9500, "diameter_solar": 1708, "mass_solar": 7,
            "surface_temp_k": 3365, "luminosity_solar": 340000,
            "constellation": "Scutum",
            "fun_facts": [
                "One of the largest known stars by radius — if placed at the Sun, surface would engulf Jupiter",
                "Despite enormous size, has less mass than Eta Carinae",
                "Discovered in 1860 during a Bonn sky survey",
                "Extreme variability makes precise measurements difficult",
            ],
        },
        "neutron star psr b1919+21": {
            "type": "star", "subtype": "pulsar",
            "distance_from_earth_ly": 2300, "rotation_hz": 0.748,
            "discovery_year": 1967, "discoverer": "Jocelyn Bell Burnell",
            "fun_facts": [
                "First pulsar ever discovered — initially nicknamed LGM-1 (Little Green Men)",
                "Discovery by Jocelyn Bell Burnell led to a Nobel Prize (controversially not awarded to her)",
                "Pulses every 1.337 seconds like a cosmic lighthouse",
                "Proved neutron stars exist — matter compressed beyond white dwarf density",
            ],
        },
        "magnetar sgr 1806-20": {
            "type": "star", "subtype": "magnetar",
            "distance_from_earth_ly": 50000,
            "magnetic_field_tesla": 1e11,
            "fun_facts": [
                "Has the strongest magnetic field ever measured in the universe",
                "A giant flare in 2004 briefly outshone the full Moon in gamma rays",
                "If it were at the Moon's distance, it would strip electrons from your atoms",
                "Magnetic field so strong it alters the structure of atoms themselves",
            ],
        },
    },
    "moons": {
        "moon": {
            "type": "moon", "parent_body": "earth", "diameter_km": 3474, "mass_kg": 7.34e22,
            "distance_from_parent_km": 384400, "orbital_period_days": 27.3,
            "surface_temp_range_c": [-173, 127], "gravity_m_s2": 1.62,
            "atmosphere": "extremely tenuous exosphere",
            "missions": ["Apollo 11-17", "Luna series", "Lunar Reconnaissance Orbiter", "Chandrayaan series", "Artemis (ongoing)"],
            "fun_facts": [
                "Only extraterrestrial body humans have visited (1969-1972)",
                "Stabilizes Earth's axial tilt, making our climate possible",
                "Slowly receding from Earth at 3.8 cm per year",
                "Formed from debris after a Mars-sized body (Theia) hit Earth",
            ],
        },
        "europa": {
            "type": "moon", "parent_body": "jupiter", "diameter_km": 3121, "mass_kg": 4.80e22,
            "distance_from_parent_km": 671100, "orbital_period_days": 3.55,
            "surface_temp_c": -160, "subsurface_ocean": True, "ocean_depth_km": 100,
            "missions": ["Voyager 1 & 2", "Galileo", "Europa Clipper (en route 2024)"],
            "habitability": "high priority candidate for extraterrestrial life",
            "fun_facts": [
                "Global subsurface liquid water ocean beneath 10-30 km of ice",
                "Ocean may contain twice as much water as all Earth's oceans",
                "Hydrothermal vents on ocean floor could support life",
                "Tidal flexing from Jupiter provides heat to keep ocean liquid",
            ],
        },
        "titan": {
            "type": "moon", "parent_body": "saturn", "diameter_km": 5150, "mass_kg": 1.35e23,
            "distance_from_parent_km": 1221870, "orbital_period_days": 15.95,
            "surface_temp_c": -179, "atmosphere": "thick N2 and methane (1.45 bar pressure)",
            "missions": ["Cassini-Huygens (Huygens landed 2005)", "Dragonfly (launching 2027)"],
            "fun_facts": [
                "Only moon with a dense atmosphere and hydrocarbon lakes",
                "Lakes of liquid methane and ethane instead of water",
                "Larger than the planet Mercury",
                "Dragonfly rotorcraft will explore its surface from 2034",
            ],
        },
        "io": {
            "type": "moon", "parent_body": "jupiter", "diameter_km": 3642, "mass_kg": 8.93e22,
            "distance_from_parent_km": 421700, "orbital_period_days": 1.77,
            "volcanism": "most volcanically active body in the solar system",
            "missions": ["Voyager 1 & 2", "Galileo", "Juno flybys"],
            "fun_facts": [
                "Has over 400 active volcanoes",
                "Volcanic plumes can reach 500 km high",
                "Surface continuously reshaped by lava — no impact craters remain",
                "Tidal squeezing by Jupiter generates intense internal heat",
            ],
        },
        "ganymede": {
            "type": "moon", "parent_body": "jupiter", "diameter_km": 5268, "mass_kg": 1.48e23,
            "distance_from_parent_km": 1070400, "orbital_period_days": 7.15,
            "magnetic_field": True, "subsurface_ocean": True,
            "missions": ["Voyager 1 & 2", "Galileo", "JUICE (en route)"],
            "fun_facts": [
                "Largest moon in the solar system — bigger than Mercury",
                "Only moon known to have its own magnetic field",
                "Has a saltwater ocean beneath its icy crust",
                "ESA's JUICE spacecraft will orbit Ganymede from 2034",
            ],
        },
        "enceladus": {
            "type": "moon", "parent_body": "saturn", "diameter_km": 504, "mass_kg": 1.08e20,
            "distance_from_parent_km": 238020, "orbital_period_days": 1.37,
            "subsurface_ocean": True, "geysers": True,
            "missions": ["Voyager 2", "Cassini"],
            "fun_facts": [
                "Shoots geysers of water ice and organic compounds from south pole",
                "Cassini flew through plumes and detected hydrogen and organics",
                "Global subsurface ocean with hydrothermal activity",
                "Top candidate for life alongside Europa",
            ],
        },
        "triton": {
            "type": "moon", "parent_body": "neptune", "diameter_km": 2707, "mass_kg": 2.14e22,
            "distance_from_parent_km": 354759, "orbital_period_days": -5.877,
            "retrograde_orbit": True, "surface_temp_c": -235,
            "missions": ["Voyager 2 (1989)"],
            "fun_facts": [
                "Only large moon that orbits opposite to its planet's rotation",
                "Likely a captured Kuiper Belt Object",
                "Coldest measured surface in the solar system",
                "Will be torn apart by Neptune's gravity in ~3.6 billion years",
            ],
        },
        "callisto": {
            "type": "moon", "parent_body": "jupiter", "diameter_km": 4821, "mass_kg": 1.08e23,
            "distance_from_parent_km": 1882700, "orbital_period_days": 16.69,
            "missions": ["Voyager 1 & 2", "Galileo", "JUICE (planned flyby)"],
            "fun_facts": [
                "Most heavily cratered object in the solar system",
                "So far from Jupiter it barely feels tidal heating",
                "May have a subsurface ocean, making it a life candidate",
                "Second largest of Jupiter's Galilean moons",
            ],
        },
        "phobos": {
            "type": "moon", "parent_body": "mars", "diameter_km": 22.4, "mass_kg": 1.07e16,
            "distance_from_parent_km": 9376, "orbital_period_hours": 7.66,
            "missions": ["Mariner 9", "Viking 1 & 2", "Mars Express", "MMX (JAXA, 2026 launch)"],
            "fun_facts": [
                "Orbits Mars faster than Mars rotates — rises in the west and sets in the east",
                "Closest moon to its planet in the solar system",
                "Moving closer to Mars by 1.8 m per century — will crash in ~50 million years",
                "JAXA's MMX mission will return a sample from Phobos",
            ],
        },
        "deimos": {
            "type": "moon", "parent_body": "mars", "diameter_km": 12.4, "mass_kg": 1.48e15,
            "distance_from_parent_km": 23460, "orbital_period_days": 1.26,
            "fun_facts": [
                "Smallest known moon in the solar system",
                "Has a very smooth surface, unlike Phobos",
                "From Mars's surface it looks like a bright star",
                "Both Martian moons are thought to be captured asteroids",
            ],
        },
        "charon": {
            "type": "moon", "parent_body": "pluto", "diameter_km": 1212, "mass_kg": 1.52e21,
            "distance_from_parent_km": 19571, "orbital_period_days": 6.39,
            "missions": ["New Horizons (2015)"],
            "fun_facts": [
                "So large relative to Pluto that the two are considered a double dwarf planet",
                "Both Pluto and Charon are tidally locked to each other",
                "Has a reddish polar cap from Pluto's atmospheric gases",
                "New Horizons revealed canyons larger than the Grand Canyon on its surface",
            ],
        },
        "titan (saturn)": {
            "type": "moon", "parent_body": "saturn", "alternate_key": "titan",
            "fun_facts": ["See 'titan' entry"],
        },
        "rhea": {
            "type": "moon", "parent_body": "saturn", "diameter_km": 1527, "mass_kg": 2.31e21,
            "distance_from_parent_km": 527108, "orbital_period_days": 4.52,
            "fun_facts": [
                "Second largest moon of Saturn",
                "Mostly ice with a small rocky core",
                "Has a thin oxygen and CO2 atmosphere — first non-Earth moon found with oxygen",
                "Cassini detected a possible debris disk around it",
            ],
        },
        "iapetus": {
            "type": "moon", "parent_body": "saturn", "diameter_km": 1469, "mass_kg": 1.81e21,
            "distance_from_parent_km": 3560820, "orbital_period_days": 79.33,
            "missions": ["Cassini"],
            "fun_facts": [
                "Has a striking two-tone surface: one hemisphere jet black, one pure white",
                "Has an enormous equatorial ridge as tall as Everest, spanning most of its circumference",
                "The dark material may come from outer solar system dust",
                "Cassini gave us the best images of this mysterious world in 2007",
            ],
        },
        "miranda": {
            "type": "moon", "parent_body": "uranus", "diameter_km": 472, "mass_kg": 6.59e19,
            "distance_from_parent_km": 129900, "orbital_period_days": 1.41,
            "missions": ["Voyager 2 (1986)"],
            "fun_facts": [
                "Has Verona Rupes — a cliff face 20 km high, tallest known in the solar system",
                "Patchwork terrain looks like random pieces stitched together",
                "May have been shattered by an impact and reassembled by gravity",
                "Only seen up close once, by Voyager 2 in 1986",
            ],
        },
        "hyperion": {
            "type": "moon", "parent_body": "saturn", "diameter_km": 270, "mass_kg": 5.62e18,
            "distance_from_parent_km": 1481100, "orbital_period_days": 21.28,
            "missions": ["Cassini"],
            "fun_facts": [
                "Has a chaotic, tumbling rotation — unpredictably changes orientation",
                "Looks like a giant sea sponge with deep craters",
                "Unusually low density suggests a porous, rubble-pile structure",
                "One of the largest non-spherical moons in the solar system",
            ],
        },
        "mimas": {
            "type": "moon", "parent_body": "saturn", "diameter_km": 396, "mass_kg": 3.75e19,
            "distance_from_parent_km": 185539, "orbital_period_days": 0.94,
            "missions": ["Cassini"],
            "fun_facts": [
                "Its giant Herschel Crater makes it look exactly like the Death Star",
                "Despite being in Saturn's ocean moon region, was long thought geologically dead",
                "Cassini data suggests a subsurface ocean or sloshing interior",
                "Smallest and innermost of Saturn's major moons",
            ],
        },
    },
    "asteroids": {
        "ceres": {
            "type": "asteroid", "subtype": "dwarf_planet", "location": "asteroid belt",
            "diameter_km": 940, "mass_kg": 9.39e20, "orbital_period_years": 4.6,
            "distance_from_sun_au": 2.77, "surface_temp_c": -105,
            "missions": ["Dawn (2015-2018)"],
            "fun_facts": [
                "Largest object in the asteroid belt",
                "Classified as both an asteroid and a dwarf planet",
                "Has water ice just below its surface",
                "Bright spots in Occator Crater are ancient salt deposits",
            ],
        },
        "vesta": {
            "type": "asteroid", "subtype": "protoplanet", "location": "asteroid belt",
            "diameter_km": 525, "mass_kg": 2.59e20, "orbital_period_years": 3.63,
            "distance_from_sun_au": 2.36,
            "missions": ["Dawn (2011-2012)"],
            "fun_facts": [
                "Second largest asteroid in the belt",
                "Has a differentiated core like a planet",
                "Giant impact crater (Rheasilvia) spans 90% of Vesta's diameter",
                "Some meteorites found on Earth came from Vesta",
            ],
        },
        "apophis": {
            "type": "asteroid", "subtype": "near_earth", "diameter_m": 370,
            "mass_kg": 2.7e10, "close_approach_year": 2029,
            "close_approach_distance_km": 31000,
            "fun_facts": [
                "Will pass closer to Earth than geostationary satellites in 2029",
                "Once had a 2.7% chance of impacting Earth in 2068 (now ruled out)",
                "Named after the Egyptian god of chaos",
                "Multiple space agencies plan to observe it during 2029 flyby",
            ],
        },
        "bennu": {
            "type": "asteroid", "subtype": "near_earth_carbonaceous", "diameter_m": 490,
            "mass_kg": 7.33e10, "orbital_period_years": 1.2,
            "missions": ["OSIRIS-REx (sample return 2023)"],
            "fun_facts": [
                "OSIRIS-REx collected 121 grams — largest asteroid sample returned",
                "Contains amino acids and organics from early solar system",
                "Small chance (~0.037%) of Earth impact in 2182",
                "Spacecraft nearly sank in on landing due to loose rubble surface",
            ],
        },
        "ryugu": {
            "type": "asteroid", "subtype": "near_earth_carbonaceous", "diameter_m": 900,
            "missions": ["Hayabusa2 (sample return 2020)"],
            "fun_facts": [
                "Hayabusa2 returned first sub-surface asteroid sample",
                "Samples contained over 20 amino acids and organic compounds",
                "Diamond-shaped with a prominent equatorial ridge",
                "One of the most carbon-rich objects ever studied",
            ],
        },
        "psyche": {
            "type": "asteroid", "subtype": "metallic", "diameter_km": 226,
            "mass_kg": 2.41e19, "location": "asteroid belt",
            "missions": ["Psyche (NASA, launched 2023, arrives 2029)"],
            "fun_facts": [
                "May be the exposed metallic core of a destroyed protoplanet",
                "Contains iron and nickel worth estimated $10 quintillion",
                "NASA launched a dedicated mission to study it",
                "Could reveal how planetary cores form",
            ],
        },
    },
    "comets": {
        "halley's comet": {
            "type": "comet", "subtype": "short_period", "period_years": 75,
            "nucleus_km": [15, 8], "last_perihelion": 1986, "next_perihelion": 2061,
            "missions": ["Giotto (ESA)", "Vega 1 & 2 (USSR)"],
            "fun_facts": [
                "Most famous comet, visible every 75 years",
                "Observed and recorded since 240 BC",
                "Halley was first to realize it returned periodically",
                "Depicted in the Bayeux Tapestry during the 1066 apparition",
            ],
        },
        "comet hale-bopp": {
            "type": "comet", "subtype": "long_period", "period_years": 2520,
            "nucleus_km": 60, "perihelion_year": 1997,
            "fun_facts": [
                "Largest comet nucleus ever observed (~60 km)",
                "Visible to naked eye for a record 18 months",
                "Two distinct ion and dust tails clearly visible",
                "Next perihelion expected around 4385 CE",
            ],
        },
        "67p/churyumov-gerasimenko": {
            "type": "comet", "subtype": "jupiter_family", "period_years": 6.44,
            "nucleus_km": [4.3, 2.6],
            "missions": ["Rosetta (ESA) — first comet orbiter + Philae lander 2014"],
            "fun_facts": [
                "First comet to be orbited AND landed on by a spacecraft",
                "Rosetta detected organic molecules, O2, and glycine",
                "Has a rubber duck shape from two lobes merging",
                "Surface temperature varies 200 C between day and night",
            ],
        },
        "neowise": {
            "type": "comet", "subtype": "long_period", "period_years": 6800,
            "discovery_year": 2020, "perihelion_year": 2020,
            "fun_facts": [
                "Brightest comet from Northern Hemisphere since Hale-Bopp (1997)",
                "Discovered by NASA's NEOWISE space telescope",
                "Displayed two tails: ion (blue) and dust (yellow-white)",
                "Will not return for approximately 6,800 years",
            ],
        },
        "shoemaker-levy 9": {
            "type": "comet", "subtype": "disrupted", "discovery_year": 1993,
            "impact_year": 1994, "impact_body": "jupiter",
            "fun_facts": [
                "First direct observation of a collision between solar system bodies",
                "Jupiter's tidal forces broke it into 21 fragments before impact",
                "Impact scars larger than Earth were visible for months",
                "Changed our understanding of Jupiter as a planetary shield",
            ],
        },
        "oumuamua": {
            "type": "comet", "subtype": "interstellar_object",
            "discovery_year": 2017, "length_m": 400, "width_m": 40,
            "fun_facts": [
                "First confirmed interstellar object detected passing through the solar system",
                "Cigar-shaped and tumbling — unlike any known solar system body",
                "Accelerated as it left the solar system, possibly from outgassing",
                "Avi Loeb controversially proposed it could be alien technology",
            ],
        },
        "borisov": {
            "type": "comet", "subtype": "interstellar_comet",
            "discovery_year": 2019, "discovery_author": "Gennady Borisov",
            "fun_facts": [
                "First confirmed interstellar comet — second interstellar visitor after Oumuamua",
                "Actually looked like a normal comet, unlike the mysterious Oumuamua",
                "Spectroscopy showed carbon monoxide-rich coma",
                "Originated from another star system unknown light-years away",
            ],
        },
        "wild 2": {
            "type": "comet", "subtype": "jupiter_family", "period_years": 6.4,
            "nucleus_km": 5,
            "missions": ["Stardust (NASA, sample return 2006)"],
            "fun_facts": [
                "NASA's Stardust collected 3,000 particles from its coma",
                "Samples contained glycine — an amino acid, building block of life",
                "Streams of jets erupt from its surface when near the Sun",
                "First comet samples returned to Earth (other than interstellar dust)",
            ],
        },
        "tempel 1": {
            "type": "comet", "subtype": "jupiter_family", "period_years": 5.5,
            "nucleus_km": 7.6,
            "missions": ["Deep Impact (2005)", "Stardust-NExT (2011)"],
            "fun_facts": [
                "NASA's Deep Impact deliberately crashed a copper impactor into it",
                "Impact revealed pristine interior material — water ice and organics",
                "Later revisited by Stardust-NExT to photograph the impact crater",
                "Its rotation period changed after the Deep Impact collision",
            ],
        },
    },
    "nebulae": {
        "orion nebula": {
            "type": "nebula", "subtype": "emission_reflection", "constellation": "Orion",
            "distance_from_earth_ly": 1344, "diameter_ly": 24, "mass_solar": 2000,
            "fun_facts": [
                "Brightest nebula visible to naked eye (magnitude 4.0)",
                "Active stellar nursery — star formation happening right now",
                "Contains the Trapezium Cluster: four massive young hot stars",
                "One of the most photographed objects in the sky",
            ],
        },
        "crab nebula": {
            "type": "nebula", "subtype": "supernova_remnant", "constellation": "Taurus",
            "distance_from_earth_ly": 6500, "diameter_ly": 11,
            "origin_supernova_year": 1054, "contains_pulsar": True, "pulsar_rotation_hz": 30,
            "fun_facts": [
                "Remnant of a supernova observed by Chinese astronomers in 1054",
                "Contains a neutron star (pulsar) spinning 30 times per second",
                "Expanding at 1500 km/s",
                "First X-ray source identified outside the solar system",
            ],
        },
        "eagle nebula": {
            "type": "nebula", "subtype": "emission", "constellation": "Serpens",
            "distance_from_earth_ly": 7000, "diameter_ly": 70,
            "contains": ["Pillars of Creation", "active star formation"],
            "fun_facts": [
                "Home to the famous 'Pillars of Creation' (Hubble 1995)",
                "Pillars are giant columns of gas and dust forming new stars",
                "JWST revealed hidden stars inside the pillars in 2022",
                "Also called M16 or NGC 6611",
            ],
        },
        "helix nebula": {
            "type": "nebula", "subtype": "planetary", "constellation": "Aquarius",
            "distance_from_earth_ly": 655, "diameter_ly": 2.87, "contains_white_dwarf": True,
            "fun_facts": [
                "Closest planetary nebula to Earth",
                "Called the 'Eye of God' — looks like a giant eye in space",
                "Formed from a Sun-like star that shed its outer layers",
                "Central white dwarf is one of the closest known",
            ],
        },
        "carina nebula": {
            "type": "nebula", "subtype": "emission", "constellation": "Carina",
            "distance_from_earth_ly": 7500, "diameter_ly": 300, "mass_solar": "millions",
            "contains": ["Eta Carinae (hypernova candidate)", "multiple star clusters"],
            "fun_facts": [
                "One of the largest nebulae known — 300 light-years across",
                "Contains Eta Carinae, one of the most massive stars known",
                "First JWST image released to the public (July 12, 2022)",
                "Home to thousands of massive young stars",
            ],
        },
        "pillars of creation": {
            "type": "nebula", "subtype": "dark_nebula_columns", "parent": "eagle nebula",
            "constellation": "Serpens", "distance_from_earth_ly": 6500, "height_ly": 4,
            "fun_facts": [
                "Iconic Hubble Space Telescope image from 1995",
                "Gas and dust columns where new stars are being born",
                "JWST imaged them in infrared revealing stars forming inside",
                "May already be destroyed by a supernova shock wave en route to us",
            ],
        },
        "ring nebula": {
            "type": "nebula", "subtype": "planetary", "constellation": "Lyra",
            "distance_from_earth_ly": 2300, "diameter_ly": 1, "contains_white_dwarf": True,
            "fun_facts": [
                "Classic example of a planetary nebula",
                "Glowing ring of ionized gas ejected by a dying star",
                "Central white dwarf is one of the hottest known (~120,000 K)",
                "JWST revealed it's actually a cylinder viewed end-on, not a ring",
            ],
        },
        "butterfly nebula": {
            "type": "nebula", "subtype": "bipolar_planetary", "constellation": "Scorpius",
            "distance_from_earth_ly": 3800, "common_names": ["Bug Nebula", "NGC 6302"],
            "central_star_temp_k": 250000,
            "fun_facts": [
                "Spectacular twin-lobed nebula resembling butterfly wings",
                "Central star is one of the hottest known (~250,000 K)",
                "Gas in the wings moves at over 950,000 km/h",
                "Hubble revealed a dusty torus hiding the central star",
            ],
        },
        "cat's eye nebula": {
            "type": "nebula", "subtype": "planetary", "constellation": "Draco",
            "distance_from_earth_ly": 3300, "catalog": "NGC 6543",
            "fun_facts": [
                "One of the most complex planetary nebulae ever observed",
                "Hubble revealed concentric shells, jets, and gas knots",
                "One of the first objects confirmed as a planetary nebula (1864)",
                "May be the product of a binary star system interaction",
            ],
        },
        "lagoon nebula": {
            "type": "nebula", "subtype": "emission", "constellation": "Sagittarius",
            "distance_from_earth_ly": 4100, "diameter_ly": 110, "catalog": "M8",
            "fun_facts": [
                "Active stellar nursery containing the Hourglass Nebula at its core",
                "Faintly visible to the naked eye from dark sites",
                "JWST revealed intricate dust pillars and star-forming cores in 2022",
                "Contains the open cluster NGC 6530, born from the nebula's gas",
            ],
        },
        "horsehead nebula": {
            "type": "nebula", "subtype": "dark_nebula", "constellation": "Orion",
            "distance_from_earth_ly": 1375, "catalog": "Barnard 33",
            "fun_facts": [
                "Dark dust cloud silhouetted against a glowing emission nebula",
                "One of the most iconic shapes in astronomy",
                "JWST captured the finest detail images ever in 2023",
                "Not visible to the naked eye — requires specialized filters or large telescope",
            ],
        },
        "veil nebula": {
            "type": "nebula", "subtype": "supernova_remnant", "constellation": "Cygnus",
            "distance_from_earth_ly": 2100, "diameter_ly": 110, "catalog": "NGC 6960 / NGC 6992",
            "age_years": 10000,
            "fun_facts": [
                "Remnant of a supernova explosion about 10,000 years ago",
                "Spans 3 degrees of sky — 6 times the width of the full Moon",
                "Delicate filaments of glowing gas still expanding at 170 km/s",
                "Hubble revealed it in stunning detail in 2015",
            ],
        },
        "rosette nebula": {
            "type": "nebula", "subtype": "emission", "constellation": "Monoceros",
            "distance_from_earth_ly": 5200, "diameter_ly": 130, "catalog": "NGC 2244",
            "fun_facts": [
                "Flower-shaped glowing nebula surrounding a young star cluster",
                "Wind from the central stars blows a central hole in the gas",
                "One of the most beautiful nebulae in the night sky",
                "Contains globules which may be forming new star systems",
            ],
        },
        "trifid nebula": {
            "type": "nebula", "subtype": "emission_reflection_dark", "constellation": "Sagittarius",
            "distance_from_earth_ly": 5200, "catalog": "M20",
            "fun_facts": [
                "Uniquely shows all three types of nebula in one object",
                "Dark lanes divide it into three lobes (hence 'trifid')",
                "Contains a young proto-binary star system at its center",
                "One of the youngest nebulae known — stellar nursery in action",
            ],
        },
        "bubble nebula": {
            "type": "nebula", "subtype": "emission", "constellation": "Cassiopeia",
            "distance_from_earth_ly": 7100, "catalog": "NGC 7635", "diameter_ly": 7,
            "fun_facts": [
                "A massive star blows a spherical bubble of ionized gas 7 light-years across",
                "The central star (BD+60°2522) is 45 times more massive than the Sun",
                "Stellar wind inflating the bubble reaches speeds of 100,000 km/h",
                "Hubble captured a stunning full-resolution mosaic for its 26th anniversary",
            ],
        },
    },
    "black_holes": {
        "sagittarius a*": {
            "type": "black_hole", "subtype": "supermassive",
            "location": "milky way galactic center", "mass_solar": 4000000,
            "schwarzschild_radius_km": 12000000, "distance_from_earth_ly": 26000,
            "first_image_year": 2022,
            "fun_facts": [
                "Supermassive black hole at the center of our Milky Way",
                "First imaged by the Event Horizon Telescope in 2022",
                "Stars orbit it at speeds up to 30 million km/h",
                "S2 star completes orbit in just 16 years, confirming the mass",
            ],
        },
        "m87*": {
            "type": "black_hole", "subtype": "supermassive", "location": "galaxy M87",
            "mass_solar": 6500000000, "distance_from_earth_mly": 55,
            "jet_length_ly": 5000, "first_image_year": 2019,
            "fun_facts": [
                "First black hole ever imaged (2019, Event Horizon Telescope)",
                "6.5 billion times more massive than the Sun",
                "Shoots a relativistic jet 5,000 light-years long",
                "The image showed the photon ring (the shadow) for the first time",
            ],
        },
        "cygnus x-1": {
            "type": "black_hole", "subtype": "stellar", "location": "cygnus constellation",
            "mass_solar": 21.2, "distance_from_earth_ly": 6070,
            "companion_star": "HDE 226868 (blue supergiant)",
            "discovery_year": 1964,
            "fun_facts": [
                "First black hole candidate ever identified",
                "Detected via X-ray emission as it consumes companion star material",
                "Stephen Hawking bet against it being a black hole (he lost)",
                "Part of a binary system with a blue supergiant companion",
            ],
        },
        "gw150914": {
            "type": "black_hole", "subtype": "binary_merger",
            "distance_from_earth_mly": 1300,
            "mass_primary_solar": 36, "mass_secondary_solar": 29, "mass_final_solar": 62,
            "energy_radiated_solar": 3, "detection_year": 2015, "detector": "LIGO",
            "fun_facts": [
                "First gravitational wave ever detected (September 14, 2015)",
                "Merger created ripples in spacetime detected on Earth",
                "3 solar masses converted to pure gravitational wave energy",
                "Led to the 2017 Nobel Prize in Physics for LIGO founders",
            ],
        },
        "ton 618": {
            "type": "black_hole", "subtype": "ultramassive_quasar",
            "mass_solar": 66000000000, "distance_from_earth_mly": 10400,
            "luminosity_solar": 140000000000000,
            "fun_facts": [
                "One of the most massive black holes known: 66 billion solar masses",
                "Powers a quasar 140 trillion times brighter than the Sun",
                "Its event horizon would extend past Pluto's orbit from our Sun",
                "Located 10.4 billion light-years away",
            ],
        },
        "phoenix a": {
            "type": "black_hole", "subtype": "ultramassive",
            "mass_solar": 100000000000, "distance_from_earth_mly": 5800,
            "location": "Phoenix Cluster center",
            "fun_facts": [
                "Possibly the most massive black hole known: ~100 billion solar masses",
                "Powers the most luminous galaxy cluster in X-rays",
                "The Phoenix Cluster around it has the highest star formation rate known",
                "Its jets inject enormous energy into the surrounding galaxy cluster",
            ],
        },
        "v616 monocerotis": {
            "type": "black_hole", "subtype": "stellar_x_ray_binary",
            "mass_solar": 9.7, "distance_from_earth_ly": 3300,
            "constellation": "Monoceros", "companion_star": "K-type orange dwarf",
            "fun_facts": [
                "Closest known black hole to Earth (A0620-00 system)",
                "Detected as a bright X-ray nova in 1975",
                "The companion star orbits the black hole every 7.75 hours",
                "Has a 'soft' X-ray spectrum showing accretion disk thermal emission",
            ],
        },
        "ss 433": {
            "type": "black_hole", "subtype": "microquasar",
            "distance_from_earth_ly": 18000, "mass_solar": 16,
            "fun_facts": [
                "Jets of matter ejected at 26% of the speed of light",
                "Precessing jets create a corkscrew pattern in space",
                "First known microquasar — a scaled-down version of quasar jets",
                "LHAASO detected ultra-high-energy gamma rays from this system",
            ],
        },
        "gw170817": {
            "type": "black_hole", "subtype": "neutron_star_merger",
            "distance_from_earth_mly": 130, "detection_year": 2017,
            "detection_method": "LIGO + Virgo + optical telescopes",
            "fun_facts": [
                "First gravitational wave event observed simultaneously in light",
                "Neutron star collision confirmed as origin of heavy elements like gold and platinum",
                "Kilonova explosion produced a billion times Earth's mass in gold",
                "Opened the era of multi-messenger astronomy",
            ],
        },
    },
    "galaxies": {
        "milky way": {
            "type": "galaxy", "subtype": "barred_spiral",
            "diameter_ly": 100000, "thickness_ly": 1000,
            "star_count": "200-400 billion", "age_billion_years": 13.6,
            "central_black_hole": "Sagittarius A*",
            "fun_facts": [
                "Our home galaxy — Earth is 26,000 light-years from the center",
                "Contains 200-400 billion stars",
                "Estimated 100-400 billion planets",
                "Will collide with Andromeda in ~4.5 billion years",
            ],
        },
        "andromeda": {
            "type": "galaxy", "subtype": "spiral", "distance_from_earth_mly": 2.537,
            "diameter_ly": 220000, "star_count": "~1 trillion", "catalog": "M31",
            "fun_facts": [
                "Largest galaxy in the Local Group",
                "Approaching the Milky Way at 110 km/s",
                "Will merge with the Milky Way in ~4.5 billion years",
                "Farthest object visible to the naked eye (M31)",
            ],
        },
        "triangulum galaxy": {
            "type": "galaxy", "subtype": "spiral", "distance_from_earth_mly": 2.73,
            "diameter_ly": 60000, "star_count": "40 billion", "catalog": "M33",
            "fun_facts": [
                "Third largest member of the Local Group",
                "Farthest object visible to the naked eye under perfect dark sky conditions",
                "Has one of the highest star formation rates in the Local Group",
                "May be gravitationally bound to Andromeda (M31)",
            ],
        },
        "large magellanic cloud": {
            "type": "galaxy", "subtype": "irregular_satellite",
            "distance_from_earth_kly": 160, "diameter_ly": 14000,
            "star_count": "30 billion", "parent_galaxy": "Milky Way",
            "fun_facts": [
                "Largest satellite galaxy of the Milky Way",
                "Visible to the naked eye from the Southern Hemisphere",
                "Contains the Tarantula Nebula — most active star-forming region known",
                "SN 1987A, the closest supernova in modern times, erupted here",
            ],
        },
        "small magellanic cloud": {
            "type": "galaxy", "subtype": "irregular_satellite",
            "distance_from_earth_kly": 200, "diameter_ly": 7000,
            "star_count": "3 billion", "parent_galaxy": "Milky Way",
            "fun_facts": [
                "Second largest satellite galaxy of the Milky Way",
                "Cepheid variables here were used by Henrietta Leavitt to discover the cosmic distance scale",
                "Connected to the LMC by a Magellanic Bridge of gas and stars",
                "Used to measure the Hubble constant in the early 20th century",
            ],
        },
        "whirlpool galaxy": {
            "type": "galaxy", "subtype": "grand_design_spiral", "catalog": "M51",
            "distance_from_earth_mly": 23, "diameter_ly": 60000,
            "companion_galaxy": "NGC 5195",
            "fun_facts": [
                "First galaxy in which spiral structure was observed (1845, Lord Rosse)",
                "Tidally interacting with companion galaxy NGC 5195",
                "One of the most studied and photographed spiral galaxies",
                "Hubble and JWST both captured stunning detailed images",
            ],
        },
        "sombrero galaxy": {
            "type": "galaxy", "subtype": "unbarred_spiral", "catalog": "M104",
            "distance_from_earth_mly": 31.1, "diameter_ly": 50000,
            "fun_facts": [
                "Named for its resemblance to a Mexican hat",
                "Has an unusually prominent dust lane and large bulge",
                "Contains a supermassive black hole of 1 billion solar masses",
                "One of the brightest galaxies within 10 megaparsecs",
            ],
        },
        "centaurus a": {
            "type": "galaxy", "subtype": "radio_galaxy_elliptical", "catalog": "NGC 5128",
            "distance_from_earth_mly": 13, "diameter_ly": 60000,
            "central_black_hole_solar": 55000000,
            "fun_facts": [
                "Closest radio galaxy to Earth — jets visible in radio and X-ray",
                "Formed from the merger of an elliptical and spiral galaxy",
                "Jets extend 13,000 light-years from the central black hole",
                "Source of ultra-high-energy cosmic rays detected by the Pierre Auger Observatory",
            ],
        },
        "black eye galaxy": {
            "type": "galaxy", "subtype": "spiral", "catalog": "M64",
            "distance_from_earth_mly": 17, "diameter_ly": 53000,
            "fun_facts": [
                "Has a dark dust band in front of its nucleus — looks like a black eye",
                "Inner and outer regions rotate in opposite directions",
                "Counter-rotating gas collision is forming new stars at the boundary",
                "Possibly formed from a merger with a smaller satellite galaxy",
            ],
        },
        "pinwheel galaxy": {
            "type": "galaxy", "subtype": "grand_design_spiral", "catalog": "M101",
            "distance_from_earth_mly": 21, "diameter_ly": 170000,
            "fun_facts": [
                "One of the largest known spiral galaxies — 170,000 light-years across",
                "Face-on orientation gives us a perfect top-down view",
                "Hosted 4 supernovae since 1900, including SN 2011fe",
                "JWST and Hubble combined images revealed unprecedented detail in 2023",
            ],
        },
        "virgo a": {
            "type": "galaxy", "subtype": "giant_elliptical", "catalog": "M87",
            "distance_from_earth_mly": 55, "diameter_ly": 120000,
            "star_count": "~1 trillion", "central_black_hole": "M87* (6.5 billion solar masses)",
            "fun_facts": [
                "Contains the first black hole ever directly imaged (2019)",
                "Its relativistic jet extends 5,000 light-years",
                "One of the most massive galaxies in the local universe",
                "Located at the center of the Virgo Cluster of galaxies",
            ],
        },
        "ic 1101": {
            "type": "galaxy", "subtype": "supergiant_elliptical",
            "distance_from_earth_mly": 1070, "diameter_ly": 6000000,
            "star_count": "100 trillion",
            "fun_facts": [
                "Largest known galaxy — 6 million light-years across (60x the Milky Way)",
                "Contains an estimated 100 trillion stars",
                "Located at the center of the Abell 2029 galaxy cluster",
                "So large that the Milky Way and Andromeda would fit inside it 2,000 times over",
            ],
        },
    },
}
