"""
Agent-narrated journeys: the journey composer turns a theme into a
structured tour (stops + narration) that the frontend camera flies.

One flagship journey is hand-crafted and served instantly (works even with
no API quota); everything else is composed live by the model.
"""

import json
import re

from app.config import CLAUDE_MODELS, MODEL_MAX_TOKENS, anthropic_key, groq_key
from app.prompts import JOURNEY_PROMPT
from app.recognition import SOLAR_BODIES

VALID_TYPES = {
    "planet", "ringed_planet", "star", "moon", "asteroid",
    "comet", "nebula", "black_hole", "galaxy",
}

GRAND_TOUR = {
    "id": "grand-tour",
    "title": "The Grand Tour",
    "subtitle": "Sunfire to the ice line — one sweep across our solar system",
    "stops": [
        {
            "name": "Sun", "kind": "solar", "type": "star", "headline": "The Engine",
            "narration": (
                "Everything begins here. The Sun holds 99.86 percent of the solar system's mass, "
                "a sphere of plasma so large that 1.3 million Earths would fit inside. Every second "
                "its core fuses 600 million tonnes of hydrogen into helium, converting four million "
                "tonnes of matter directly into light. The photons leaving its surface now spent up "
                "to 100,000 years fighting their way out from the core. If the Sun were a basketball, "
                "Earth would be a sesame seed 26 meters away. Hold that scale in mind — this tour "
                "covers four and a half billion kilometers."
            ),
        },
        {
            "name": "Mercury", "kind": "solar", "type": "planet", "headline": "The Scorched Relic",
            "narration": (
                "Mercury is a world of brutal extremes: 430 degrees Celsius at noon, minus 180 at "
                "night — the largest temperature swing of any planet. It is the smallest planet, "
                "barely larger than our Moon, yet unnervingly dense: an iron core fills 85 percent "
                "of its radius, likely the survivor of a colossal ancient impact that stripped its "
                "mantle away. A day here outlasts its year. And in permanently shadowed polar "
                "craters, where sunlight has not fallen for billions of years, MESSENGER found "
                "water ice — frost clinging to the planet closest to the fire."
            ),
        },
        {
            "name": "Earth", "kind": "solar", "type": "planet", "headline": "The Anomaly",
            "narration": (
                "Every experiment, every civilization, every love story in known history happened "
                "on this pale blue sphere. Earth is the only world where confirmed liquid water "
                "oceans meet continents under an oxygen sky — an atmosphere that is itself a "
                "biosignature, continuously manufactured by life. Its magnetic field, generated by "
                "a spinning iron core, deflects the solar wind that long ago stripped Mars bare. "
                "Seen from Saturn by Cassini in 2013, Earth is a single pixel of light. Carl Sagan "
                "said it best: everyone you have ever heard of lived out their lives on that mote "
                "of dust suspended in a sunbeam."
            ),
        },
        {
            "name": "Mars", "kind": "solar", "type": "planet", "headline": "The Unfinished World",
            "narration": (
                "Mars is a planet that stopped halfway. Riverbeds, deltas, and lake floors are "
                "carved across its surface — Perseverance is driving through an ancient river delta "
                "right now — yet the water is gone, lost when the planet's magnetic field died and "
                "the solar wind tore its atmosphere into space. Olympus Mons rises 21 kilometers, "
                "nearly three Everests, and Valles Marineris would stretch from New York to Los "
                "Angeles. Mars is small, cold, and quiet — but it is the only other world where "
                "humans have seriously planned an address."
            ),
        },
        {
            "name": "Jupiter", "kind": "solar", "type": "planet", "headline": "King of Worlds",
            "narration": (
                "Jupiter is not just the largest planet — it outweighs every other planet combined, "
                "two and a half times over. Its Great Red Spot is a storm wider than Earth that has "
                "raged for at least 350 years. Its magnetic field is the largest structure in the "
                "solar system after the Sun's own; if it glowed visibly, it would span five full "
                "Moons in our night sky. Jupiter is a failed star's shadow and the system's "
                "gravitational bouncer, hurling comets away from the inner worlds. Around it orbit "
                "worlds that are destinations in their own right — one of them hides an ocean."
            ),
        },
        {
            "name": "Europa", "kind": "solar", "type": "moon", "headline": "The Hidden Ocean",
            "narration": (
                "Beneath Europa's cracked shell of ice lies more liquid water than in all of "
                "Earth's oceans combined — a global sea 60 to 150 kilometers deep, kept warm for "
                "four billion years by Jupiter's tidal kneading. The rust-colored fractures "
                "crossing its face are seams where that ocean may have reached the surface. On "
                "Earth, wherever there is water, energy, and chemistry, there is life. Europa has "
                "all three. NASA's Europa Clipper, launched in 2024, arrives in 2030 to fly through "
                "its possible plumes. This small moon is the most promising place beyond Earth to "
                "answer the oldest question we have."
            ),
        },
        {
            "name": "Saturn", "kind": "solar", "type": "ringed_planet", "headline": "The Crown",
            "narration": (
                "Saturn's rings span 280,000 kilometers yet average just ten meters thick — "
                "proportionally thinner than a sheet of paper the size of a city. They are made of "
                "countless shards of nearly pure water ice, shepherded by moons, and they are "
                "temporary: ring rain is draining them into the planet, and in 100 million years "
                "they may be gone. We exist in the brief age when Saturn is crowned. Cassini spent "
                "13 years here before diving into the planet itself in 2017, and on its moon "
                "Titan, a lander built by humans rests on the shore of a methane world. This is "
                "how far our reach already extends. The universe is not somewhere else — you are "
                "standing in it."
            ),
        },
    ],
}

PRESET_THEMES = [
    {"id": "grand-tour", "title": "The Grand Tour", "subtitle": "Sunfire to the ice line across our solar system", "builtin": True},
    {"id": "star-death", "title": "Death of Stars", "subtitle": "From red giants to supernovae, pulsars and black holes", "builtin": False,
     "theme": "The life and death of stars: follow stellar evolution from a sun-like star through red giant, planetary nebula, white dwarf, then massive stars to supernova, neutron star and black hole"},
    {"id": "ocean-worlds", "title": "Ocean Worlds", "subtitle": "The solar system's hidden seas and where life might swim", "builtin": False,
     "theme": "Ocean worlds of the solar system: Europa, Enceladus, Titan and the search for life in subsurface oceans"},
    {"id": "edge-of-night", "title": "Edge of Night", "subtitle": "Outward past the ice giants to interstellar space", "builtin": False,
     "theme": "A journey outward from Uranus and Neptune through the Kuiper belt, past Pluto, to the heliopause and interstellar space where the Voyagers fly"},
]


def _extract_json(text: str) -> dict:
    """Parse model output into JSON, tolerating fences and prose margins."""
    cleaned = re.sub(r"^```(json)?|```$", "", text.strip(), flags=re.M).strip()
    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        start, end = cleaned.find("{"), cleaned.rfind("}")
        if start >= 0 and end > start:
            return json.loads(cleaned[start:end + 1])
        raise


def _validate(journey: dict) -> dict:
    title = str(journey.get("title") or "Untitled Journey")[:90]
    subtitle = str(journey.get("subtitle") or "")[:140]
    stops_in = journey.get("stops") or []
    stops = []
    for s in stops_in[:8]:
        name = str(s.get("name") or "").strip()[:60]
        narration = str(s.get("narration") or "").strip()[:1600]
        if not name or len(narration) < 40:
            continue
        obj_type = str(s.get("type") or "planet").strip()
        if obj_type not in VALID_TYPES:
            obj_type = "planet"
        kind = "solar" if (
            str(s.get("kind")) == "solar" and name.lower() in SOLAR_BODIES
        ) else "deep"
        stops.append({
            "name": name,
            "kind": kind,
            "type": obj_type,
            "headline": str(s.get("headline") or "")[:80],
            "narration": narration,
        })
    if len(stops) < 2:
        raise ValueError("Journey has too few valid stops")
    return {"title": title, "subtitle": subtitle, "stops": stops}


async def compose_journey(theme: str, model: str) -> dict:
    """Compose a journey with the requested model. Raises on failure —
    the API layer translates to a clean HTTP error."""
    if model in CLAUDE_MODELS:
        from anthropic import AsyncAnthropic

        key = anthropic_key()
        if not key:
            raise RuntimeError("ANTHROPIC_API_KEY is not set")
        client = AsyncAnthropic(api_key=key)
        msg = await client.messages.create(
            model=model,
            max_tokens=3000,
            system=JOURNEY_PROMPT,
            messages=[{"role": "user", "content": f"Theme: {theme}"}],
        )
        text = "".join(b.text for b in msg.content if b.type == "text")
    else:
        from groq import AsyncGroq

        key = groq_key()
        if not key:
            raise RuntimeError("GROQ_API_KEY is not set")
        client = AsyncGroq(api_key=key)
        resp = await client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": JOURNEY_PROMPT},
                {"role": "user", "content": f"Theme: {theme}"},
            ],
            response_format={"type": "json_object"},
            max_tokens=min(3000, MODEL_MAX_TOKENS.get(model, 3000)),
        )
        text = resp.choices[0].message.content or ""

    return _validate(_extract_json(text))
